spring.application.name=medical-store-app

# DB Connection
spring.datasource.url=jdbc:mysql://localhost:3306/medical_store_db
spring.datasource.username=root
spring.datasource.password=Mitesh21@7
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA (optional but helpful)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# To see logs clearly
logging.level.org.springframework=INFO